# Generated by Django 3.2.12 on 2022-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webking',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
