# Generated by Django 3.2.12 on 2022-04-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_webking_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webking',
            name='message',
        ),
    ]
