# Generated by Django 3.2.12 on 2022-04-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=200)),
                ('web_desing', models.CharField(max_length=200)),
                ('responsive_web', models.CharField(max_length=200)),
                ('web_speed', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
