# Generated by Django 3.2.12 on 2022-04-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='age',
            field=models.IntegerField(),
        ),
    ]
